# Generated by Django 5.0.8 on 2025-02-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_total_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanstatus',
            name='single_Installments',
            field=models.FloatField(default=1),
        ),
    ]
